/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Driver {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'vehicleTypeName' : string,
  'rating' : bigint,
  'phone' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'estimatedPrice' : bigint,
  'createdAt' : bigint,
  'assignedDriverId' : [] | [bigint],
  'pickupAddress' : string,
  'customerId' : string,
  'dropAddress' : string,
  'vehicleTypeId' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VehicleType {
  'id' : bigint,
  'capacityDescription' : string,
  'name' : string,
  'perKmRate' : bigint,
  'isActive' : boolean,
  'iconEmoji' : string,
  'basePrice' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addServiceArea' : ActorMethod<[string], undefined>,
  'addVehicleType' : ActorMethod<[VehicleType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDriverToOrder' : ActorMethod<[bigint, bigint], undefined>,
  'createOrder' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'getActiveVehicleTypes' : ActorMethod<[], Array<VehicleType>>,
  'getAllDrivers' : ActorMethod<[], Array<Driver>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleServiceAreaActive' : ActorMethod<[bigint], undefined>,
  'toggleVehicleTypeActive' : ActorMethod<[bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateVehicleType' : ActorMethod<[bigint, VehicleType], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];