/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Record({
  'id' : IDL.Nat,
  'capacityDescription' : IDL.Text,
  'name' : IDL.Text,
  'perKmRate' : IDL.Nat,
  'isActive' : IDL.Bool,
  'iconEmoji' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Driver = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'vehicleTypeName' : IDL.Text,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'estimatedPrice' : IDL.Nat,
  'createdAt' : IDL.Int,
  'assignedDriverId' : IDL.Opt(IDL.Nat),
  'pickupAddress' : IDL.Text,
  'customerId' : IDL.Text,
  'dropAddress' : IDL.Text,
  'vehicleTypeId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addServiceArea' : IDL.Func([IDL.Text], [], []),
  'addVehicleType' : IDL.Func([VehicleType], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDriverToOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getActiveVehicleTypes' : IDL.Func([], [IDL.Vec(VehicleType)], ['query']),
  'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleServiceAreaActive' : IDL.Func([IDL.Nat], [], []),
  'toggleVehicleTypeActive' : IDL.Func([IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateVehicleType' : IDL.Func([IDL.Nat, VehicleType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Record({
    'id' : IDL.Nat,
    'capacityDescription' : IDL.Text,
    'name' : IDL.Text,
    'perKmRate' : IDL.Nat,
    'isActive' : IDL.Bool,
    'iconEmoji' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Driver = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'vehicleTypeName' : IDL.Text,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'estimatedPrice' : IDL.Nat,
    'createdAt' : IDL.Int,
    'assignedDriverId' : IDL.Opt(IDL.Nat),
    'pickupAddress' : IDL.Text,
    'customerId' : IDL.Text,
    'dropAddress' : IDL.Text,
    'vehicleTypeId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addServiceArea' : IDL.Func([IDL.Text], [], []),
    'addVehicleType' : IDL.Func([VehicleType], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDriverToOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getActiveVehicleTypes' : IDL.Func([], [IDL.Vec(VehicleType)], ['query']),
    'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleServiceAreaActive' : IDL.Func([IDL.Nat], [], []),
    'toggleVehicleTypeActive' : IDL.Func([IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateVehicleType' : IDL.Func([IDL.Nat, VehicleType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };